### ISSUE TITLE
game.js sintax error

### ISSUE THREAD

**Issue by pgsfredda** [textadventures/quest-js#5]
Hi.
I don't use windows so I think to use quest-js to publish my quest adventures. Thanks a lot for your job.

game.js - templates.t_GiveToMenu: you used twice double quote for concatening objects var in the string. You have to use a single quote and double quote.

Thank you

**Comment by alexwarren** [comment]
questjs isn't being developed any more, but the good news is that I'm working on v6 of Quest, which will have a cross-platform Quest Player. Hopefully a preview version will be available in a few months. https://github.com/textadventures/quest/tree/v6
